modLoader = "javafml" #mandatory
loaderVersion = "*"
license = "${license}" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/MapleMods/Sapling/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    logoFile = "${mod_id}.png"
    credits = "${credits}"
    authors = "${mod_author}"
    description = '''${description}'''

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"