modLoader = "javafml"
loaderVersion = "*"
license = "${license}"
issueTrackerURL="https://github.com/MapleMods/Sapling/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    logoFile="${mod_id}.png"
    credits="${credits}"
    authors = "${mod_author}"
    description = '''${description}'''

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"